# Generated by Django 4.1.7 on 2023-02-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0002_user_patronymic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='added',
            name='connects',
            field=models.CharField(max_length=255, null=True, verbose_name='pass connects'),
        ),
    ]
