# Generated by Django 4.1.7 on 2023-02-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0003_alter_added_connects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cords',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cords',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
